version: '2'

networks:
  kafka-network:
    driver: bridge

services:
  kafka101:
    image: 'bitnami/kafka:3.4'
    networks:
      - kafka-network
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_NODE_ID=101
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=101@kafka101:9093,102@kafka102:9093,103@kafka103:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LOG_DIR=/bitnami/kafka/data
      - KAFKA_KRAFT_CLUSTER_ID=h5YBEzcIRjixjNEe83n19Q

  kafka102:
    image: 'bitnami/kafka:3.4'
    networks:
      - kafka-network
    environment:
      - KAFKA_CFG_NODE_ID=102
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=101@kafka101:9093,102@kafka102:9093,103@kafka103:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LOG_DIR=/bitnami/kafka/data
      - KAFKA_KRAFT_CLUSTER_ID=h5YBEzcIRjixjNEe83n19Q

  kafka103:
    image: 'bitnami/kafka:3.4'
    networks:
      - kafka-network
    environment:
      - KAFKA_CFG_NODE_ID=103
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=101@kafka101:9093,102@kafka102:9093,103@kafka103:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LOG_DIR=/bitnami/kafka/data
      - KAFKA_KRAFT_CLUSTER_ID=h5YBEzcIRjixjNEe83n19Q
